version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PASSWORD: password123
      POSTGRES_DB: flask_lesson
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: postgres
    restart: always
    user: root
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d